gText_Birch_Welcome::
	.string "Oi! Desculpe por fazê-lo esperar!\p"
	.string "Bem-vindo ao mundo dos POKéMON!\p"
	.string "Meu nome é BIRCH.\p"
	.string "Mas todos me chamam de\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Isso é o que chamamos de “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Este mundo é amplamente habitado por\n"
	.string "criaturas conhecidas como POKéMON.\p"
	.string "Nós, humanos, vivemos ao lado dos\n"
	.string "POKéMON, às vezes como amigos, e\l"
	.string "às vezes como colegas de trabalho.\p"
	.string "E, às vezes, nos unimos e\n"
	.string "batalhamos com outros como nós.\p"
	.string "Mas, apesar da nossa proximidade,\n"
	.string "näo sabemos tudo sobre os POKéMON.\p"
	.string "Na verdade, há muitos, muitos\n"
	.string "mistérios em torno dos POKéMON.\p"
	.string "Para desvendar os segredos dos\n"
	.string "POKéMON, tenho feito pesquisas.\l"
	.string "É isso que eu faço.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E você é?$"

gText_Birch_BoyOrGirl::
	.string "Você é um menino?\n"
	.string "Ou é uma menina?$"

gText_Birch_WhatsYourName::
	.string "Certo.\n"
	.string "Qual é o seu nome?$"

gText_Birch_SoItsPlayer::
	.string "Entäo é {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, entendi!\p"
	.string "Você é {PLAYER}{KUN}, que está se mudando\n"
	.string "para minha cidade natal, LITTLEROOT.\l"
	.string "Agora entendi!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Muito bem, está pronto?\p"
	.string "Sua própria aventura está prestes\n"
	.string "a começar.\p"
	.string "Tenha coragem e mergulhe no\n"
	.string "mundo dos POKéMON, onde sonhos,\l"
	.string "aventura e amizades o aguardam!\p"
	.string "Bem, estarei esperando por você depois.\n"
	.string "Venha me ver no meu LABORATÓRIO.\p"
	.string "$"
