Text_BootUpPC:
	.string "{JOGADOR} ligou o PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Qual PC deve ser acessado?$"

gText_AccessedSomeonesPC::
	.string "Acessou o PC de ALGUéM.$"

gText_StorageSystemOpened::
	.string "Sistema de Armazenamento\n"
	.string "POKéMON aberto.$"

gText_AccessedPlayersPC::
	.string "Acessou o PC de {JOGADOR}.$"

gText_AccessedLanettesPC::
	.string "Acessou o PC da LANETTE.$"
