Text_BootUpPC:
	.string "{PLAYER} ligou o PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Qual PC deve ser acessado?$"

gText_AccessedSomeonesPC::
	.string "Acessou o PC de alguém.$"

gText_StorageSystemOpened::
	.string "Sistema de Armazenamento\n"
	.string "POKéMON aberto.$"

gText_AccessedPlayersPC::
	.string "Acessou o PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Acessou o PC da LANETTE.$"
