gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} foi transferido para\n"
	.string "o PC de ALGUéM.\p"
	.string "Foi colocado na\n"
	.string "CAIXA “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} foi transferido para\n"
	.string "o PC da LANETTE.\p"
	.string "Foi colocado na\n"
	.string "CAIXA “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” no\n"
	.string "PC de ALGUéM está cheio.\p"
	.string "{STR_VAR_2} foi transferido para\n"
	.string "a CAIXA “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOX “{STR_VAR_3}” no\n"
	.string "PC da LANETTE está cheio.\p"
	.string "{STR_VAR_2} foi transferido para\n"
	.string "a CAIXA “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Näo tem mais espaço para\n"
	.string "os POKéMON!\p"
	.string "As CAIXAS POKéMON\n"
	.string "näo podem aceitar mais nenhum!$"

gText_NicknameThisPokemon::
	.string "Quer dar um apelido para\n"
	.string "esse {STR_VAR_1}?$"
