gText_WouldYouLikeToRestYourPkmn::
	.string "Olá, e seja bem-vindo ao\n"
	.string "CENTRO POKéMON.\p"
	.string "Nós restauramos seus POKéMONs\n"
	.string "cansados para a saúde completa.\p"
	.string "Você gostaria de descansar\n"
	.string "seu POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Certo, vou pegar seu POKéMON\n"
	.string "por alguns segundos.$"

gText_RestoredPkmnToFullHealth::
	.string "Obrigado por esperar.\p"
	.string "Restauramos seu POKéMON\n"
	.string "para a saúde completa.$"

gText_WeHopeToSeeYouAgain::
	.string "Esperamos vê-lo novamente!$"

gText_WelcomeCutShort::
	.string "Olá, e seja bem-vindo ao\n"
	.string "CENTRO POKéMON.\p"
	.string "Nós restauramos seus POKéMONs\n"
	.string "cansados para a saúde completa.\p"
	.string "Você gostaria de…\n"

gText_NoticesGoldCard::
	.string "E-e-es-sa carta…\n"
	.string "Será… O CARTÃO DE OURO?!\p"
	.string "Oh, a cor dourada é brilhante!\n"
	.string "As quatro estrelas parecem brilhar!\p"
	.string "Já vi vários TREINADORES com um\n"
	.string "CARTÃO DE PRATA antes, mas, {PLAYER},\l"
	.string "você é o primeiro TREINADOR que eu já\l"
	.string "vi com um CARTÃO DE OURO!\p"
	.string "Ok, {PLAYER}, por favor, permita-me\n"
	.string "a honra de descansar seus POKéMON!$"

gText_YouWantTheUsual::
	.string "Estou encantado em vê-lo, {PLAYER}!\n"
	.string "Você quer o de sempre, certo?$"

gText_IllTakeYourPkmn2::
	.string "Certo, vou pegar seus POKéMON\n"
	.string "por alguns segundos.$"

gText_ThankYouForWaiting::
	.string "Obrigado por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "Esperamos vê-lo novamente!$"