	.align 2
gText_ConfirmSave::
	.string "Quer salvar o jogo?$"

gText_AlreadySavedFile::
	.string "Já existe um arquivo salvo.\n"
	.string "Tudo bem sobrescrevê-lo?$"

gText_SavingDontTurnOff::
	.string "SALVANDO…\n"
	.string "NÄO DESLIGUE O SISTEMA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} salvou o jogo.$"

gText_DifferentSaveFile::
	.string "AVISO!\p"
	.string "Já existe um arquivo de jogo\n"
	.string "diferente salvo.\p"
	.string "Se você salvar agora, a outra\n"
	.string "aventura, incluindo itens e\l"
	.string "POKéMON, será completamente perdida.\p"
	.string "Tem certeza de que quer salvar agora\n"
	.string "e sobrescrever o outro arquivo?$"

gText_SaveError::
	.string "Erro ao salvar.\p"
	.string "Por favor, troque a\n"
	.string "memória de backup.$"

gText_SavingDontTurnOffPower::
	.string "SALVANDO…\n"
	.string "NÄO DESLIGUE O SISTEMA.$"
