name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout syms
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@master
        with:
          path: symbols
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} all

      - name: Rename pokeemerald_modern.gba
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
          mv pokeemerald_modern.gba esmeralda-ptbr-$GITHUB_SHA_SHORT.gba

      - name: Post to Telegram channel
        if: ${{ success() && github.ref == 'refs/heads/master' && github.ref_type != 'tag' }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
            export output=esmeralda-ptbr-$GITHUB_SHA_SHORT.gba

            # Criando a legenda personalizada para o Telegram
            TELEGRAM_CAPTION="Novo Build: esmeralda-ptbr-$GITHUB_SHA_SHORT.gba%0ACommit: $COMMIT_MESSAGE%0AAutor: $COMMIT_AUTHOR%0ACommit URL: $COMMIT_URL"

            # Enviar para o Telegram
            curl -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
              -d "chat_id=${CHANNEL_ID}" \
              -d "text=${TELEGRAM_CAPTION}" \
              -d "parse_mode=HTML"
          fi
        continue-on-error: true

      - name: Upload to GitHub Releases (as pre-release)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: esmeralda-ptbr-${{ github.sha }}.gba
          asset_name: esmeralda-ptbr-${{ github.sha }}.gba
          tag: "release-${{ github.run_number }}"  